### ISSUE TITLE
Incompatibility with OpenSSL 1.0.1g interface

### ISSUE THREAD

**Issue by dandrestor** [libressl/portable#573]
According to the README, LibreSSL is API-compatible with OpenSSL 1.0.1g. I'm seeing an incompatibility though for this function:
```
const BIO_METHOD *BIO_s_mem(void);
```
In OpenSSL 1.0.1g, the return value is non-`const`, as seen here: https://github.com/openssl/openssl/blob/b2d951e4232d2f90168f9a3dd0b7df9ecf2d81a8/crypto/bio/bio.h#L667

This causes problems with the following:
```
#if (OPENSSL_VERSION_NUMBER >= 0x10100000L) && (OPENSSL_VERSION_NUMBER < 0x20000000L)
            const BIO_METHOD* bio_method;
#else
            BIO_METHOD* bio_method;
#endif
            bio_method = BIO_s_mem();
```

**Question 1:** Is this a bug in LibreSSL or am I using it wrong? (Maybe LibreSSL is not supposed to be a drop-in replacement for OpenSSL?)

**Question 2:** `OPENSSL_VERSION_NUMBER` seems to be always set to `0x20000000L` with LibreSSL. Would that not break client code that uses this macro to support multiple OpenSSL versions, such as in my example above?

**Comment by kinichiro** [comment]
change was done by this commit https://github.com/libressl-portable/openbsd/commit/703abab3212b397d500bd8c2f5f7ee6b03feb159

**Comment by 4a6f656c** [comment]
LibreSSL tries to be compatible with OpenSSL where possible and is largely compatible with 1.0.1 and newer versions - the const changed referenced is specifically due to newer code needing to adapt to OpenSSL 1.1.1 APIs.

> **Question 1:** Is this a bug in LibreSSL or am I using it wrong? (Maybe LibreSSL is not supposed to be a drop-in replacement for OpenSSL?)

No, it is not a bug in LibreSSL - it is one of the interfaces that have been changed to follow OpenSSL 1.1.1. It is intended to be a drop-in replacement, but there will always be corner cases.

> **Question 2:** `OPENSSL_VERSION_NUMBER` seems to be always set to `0x20000000L` with LibreSSL. Would that not break client code that uses this macro to support multiple OpenSSL versions, such as in my example above?

LibreSSL bumped `OPENSSL_VERSION_NUMBER` early on - unfortunately there is a lot of code that checks version rather than actual feature/function available and without doing this, many of the new features would not be detected/used. `LIBRESSL_VERSION_NUMBER` exists if you really need to use it.

That said, I'm not sure why someone would write code that uses `(OPENSSL_VERSION_NUMBER >= 0x10100000L) && (OPENSSL_VERSION_NUMBER < 0x20000000L)` - that seems like a rather strange version check, even by OpenSSL standards.

**Comment by dandrestor** [comment]
Well that's unfortunate. The interface has diverged to a point where it's inconsistent from an OpenSSL perspective. Would it be feasible for the interface of `BIO_s_mem()` to be changed to be consistent with `OPENSSL_VERSION_NUMBER` as reported by LibreSSL?

> That said, I'm not sure why someone would write code that uses `(OPENSSL_VERSION_NUMBER >= 0x10100000L) && (OPENSSL_VERSION_NUMBER < 0x20000000L)` - that seems like a rather strange version check, even by OpenSSL standards.

[Ask Microsoft](https://github.com/search?q=org%3AAzure+%28OPENSSL_VERSION_NUMBER+%3E%3D+0x10100000L%29+%26%26+%28OPENSSL_VERSION_NUMBER+%3C+0x20000000L%29&type=Code)

**Comment by bob-beck** [comment]
If you want to do that, you should be probably be looking at LIBRESSL_VERSION to decide
amongst versions of libressl.

**Comment by dandrestor** [comment]
Yeah, but having to do that does conflict with the stated purpose of LibreSSL being a drop-in replacement for OpenSSL. The interfaces (in this particular case) are simply not the same.

**Comment by gabezal** [comment]
Just bumped into this issue while trying to build a project on OpenBSD which uses `#if OPENSSL_VERSION_NUMBER >= 0x1010100fL` to "detect" `SSL_CTX_set_ciphersuites()` availability.
