### ISSUE TITLE
X509_STORE_CTX_get_check_issued missing

### ISSUE THREAD

**Issue by ccvca** [libressl/portable#748]
In Version 3.5 the members of `X509_STORE_CTX` are set to private and access functions are defined. But unlike in OpenSSL, there ist no function to get the `check_issued` member.
In OpenSSL 1.1.1 this function is named `X509_STORE_CTX_get_check_issued` and it is described in the [docs here](https://www.openssl.org/docs/man1.1.1/man3/X509_STORE_CTX_get_check_issued.html).

**Comment by botovq** [comment]
We typically only add accessors when we see evidence that they are used
somewhere in the open source ecosystem.

What is the use case and what uses this?

**Comment by ccvca** [comment]
I came accross this, when I port the open62541 OPC UA implementation to LibreSSL 3.5 (I'm not the author of the OpenSSL Implementation)

The function is used twice in this file:
https://github.com/open62541/open62541/blob/ea3d7b31454f0514e6c67eab474ea8d4e5d9e7f1/plugins/crypto/openssl/ua_pki_openssl.c#L506

**Comment by botovq** [comment]
On LibreSSL these calls are equivalent to checking that

    X509_check_issued(certificateX509, certificateX509) != X509_V_OK

https://github.com/libressl-portable/openbsd/blob/master/src/lib/libcrypto/x509/x509_vfy.c#L682
since the X509_V_FLAG_CB_ISSUER_CHECK isn't set (it was deprecated in
OpenSSL 1.1.0)

On OpenSSL this should also be the case.

I may be missing a subtlety but I do not currently see why reaching for
the store's internal check_issued() function is desirable or necessary
here.

**Comment by 4a6f656c** [comment]
`X509_STORE_CTX_get_check_issued()` is available in LibreSSL 3.7.1 and newer.
