### ISSUE TITLE
Release notifications

### ISSUE THREAD

**Issue by andy5995** [libressl/portable#813]
I think if you draft releases instead of pushing tags, then GitHub users who are watching releases on your repo will get email notifications (tags can be created when you draft a release).

A related discussion at https://github.com/OpenRC/openrc/discussions/580 ;)

**Comment by botovq** [comment]
Thanks. We use github for CI/Fuzzing/etc, and for some user interactions, but otherwise it's not our principal development environment. I'd much rather reduce the amount of time I need to spend in my browser in general and on this website in particular. People in need of email release announcements can subscribe to `libressl@openbsd.org`.

**Comment by andy5995** [comment]
That makes sense, thanks for the FYI
