### ISSUE TITLE
Patch failure while building from source on master during ./autogen.sh

### ISSUE THREAD

**Issue by quapka** [libressl/portable#814]
I have tried to build `master` (`3c1e882d259e`) using the instructions from `README.md`. The very first step, i.e. running `./autogen.sh` fails:

```
❯ ./autogen.sh
pulling upstream openbsd source
Cloning into 'openbsd'...
remote: Enumerating objects: 144811, done.
remote: Counting objects: 100% (26496/26496), done.
remote: Compressing objects: 100% (13585/13585), done.
remote: Total 144811 (delta 12231), reused 23554 (delta 11745), pack-reused 118315
Receiving objects: 100% (144811/144811), 50.70 MiB | 10.45 MiB/s, done.
Resolving deltas: 100% (103980/103980), done.
Updating files: 100% (13680/13680), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
libcrypto version 50:1:0
libssl version 53:1:0
libtls version 26:1:0
LibreSSL version 3.7.1
copying libcrypto source
generating arm ASM source for elf
generating x86_64 ASM source for elf
generating x86_64 ASM source for macosx
generating x86_64 ASM source for masm
generating x86_64 ASM source for mingw64
copying libtls source
copying nc(1) source
copying ocspcheck(1) source
copying openssl(1) source
copying libssl source
copying tests
patching file tests/aeadtest.c
patching file include/openssl/bio.h
patching file crypto/bn/bn_div.c
Hunk #1 FAILED at 89.
1 out of 1 hunk FAILED -- saving rejects to file crypto/bn/bn_div.c.rej

❯ bat crypto/bn/bn_div.c.rej
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: crypto/bn/bn_div.c.rej
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ --- openbsd/src/lib/libcrypto/bn/bn_div.c   2018-08-03 22:40:06.596555542 -0500
   2   │ +++ crypto/bn/bn_div.c  2019-01-20 19:26:37.891450640 -0600
   3   │ @@ -89,7 +89,7 @@
   4   │         q;                  \
   5   │     })
   6   │  #  define REMAINDER_IS_ALREADY_CALCULATED
   7   │ -#  elif defined(__x86_64)
   8   │ +#  elif defined(__x86_64) && defined(_LP64)
   9   │     /*
  10   │      * Same story here, but it's 128-bit by 64-bit division. Wow!
  11   │      *                  <appro@fy.chalmers.se>
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

**Comment by busterb** [comment]
@quapka understood. We'll get to updating it later this week. This happens occasionally when upstream code has gotten too far ahead of this project. Feel free to use one of the stable branches in the mean time.

**Comment by quapka** [comment]
I see; no worries.

**Comment by orbea** [comment]
Perhaps it would make sense to somehow merge the repos? IMO it would be far less complicated to work with libressl if there was a shared repo that could elegantly meet everyone's needs, but maybe I'm overlooking the reasons why this arrangement exists?

**Comment by botovq** [comment]
The libressl/openbsd repo is automatically converted from the OpenBSD
cvs tree (where the actual commits happen). It has to be separate from
the -portable repo because of how the conversion tools work.

I have long been wondering if it would not make more sense to have the
openbsd repo as a git submodule of the portable repo. As much of a pain
as git submodules generally are, it feel like the appropriate setup here.

**Comment by orbea** [comment]
There are also git subtrees.

https://www.atlassian.com/git/tutorials/git-subtree

**Comment by lstipakov** [comment]
What @J08nY said - shouldn't `OPENBSD_BRANCH` in `v3.7.0` tag point to `libressl-v3.7.0` tag of https://github.com/libressl/openbsd instead of `master`?

May we expect it to be fixed soon? This [breaks](https://github.com/lstipakov/openvpn/actions/runs/4132544568/jobs/7141369946#step:4:51) GHA build automation for OpenVPN.

**Comment by busterb** [comment]
Some background:

We don't use git submodules or subtrees because the conversion process from OpenBSD's CVS to Git does not currently create stable Git hashes. That's because it doesn't pull in the whole tree, unlike https://github.com/openbsd/src, but a subset of paths which can bring in file history due to how file moves look in CVS, that to git, look like a rewrite of history. That would cause havoc on any mechanism that relies or points tocommit hashes on the openbsd repo. You'd wind up with historical tags that couldn't be built either.

The tags in the 'openbsd' repo do not point to stable hashes either, and are created dynamically _after_ after a release is tagged and shipped, and they're really only published for the sake of Github users. The repo that the actual development here happens with also does not have these tags on the openbsd side.

Normally to avoid this problem, we either just don't ever push intermediate work to Github, or tried to fix it as fast as possible so few people complain or notice. In this case, we just needed to sync for this week's stable releases, but it happened in the middle of a work week, so we haven't had the time to fix all the churn in master immediately (day job, family, natural disasters, etc.)

We could set OPENBSD_BRANCH temporarily to fix Github builds, or just agree that it's OK to be broken one more day until one of us has time to fix it this coming weekend. I do not relish the idea of having to make commits that alternate OPENBSD_BRANCH from tag to master and back in order to make progress on development though, so this doesn't seem like a long-term solution.

What would be good I think is if we could switch to a submodule/subtree path based on some stable git hash conversion scheme. If there's a way to piggy-back on https://github.com/openbsd/src which doesn't have the hash stability issue since it uses different conversion tooling since it operates on the whole CVS history, that'd be nice.

I'd also like to avoid forcing everyone to download the whole OpenBSD source tree just to build LibreSSL though.

Is there a way to satisfy both constraints?

**Comment by J08nY** [comment]
> We could set OPENBSD_BRANCH temporarily to fix Github builds, or just agree that it's OK to be broken one more day until one of us has time to fix it this coming weekend. I do not relish the idea of having to make commits that alternate OPENBSD_BRANCH from tag to master and back in order to make progress on development though, so this doesn't seem like a long-term solution.

Oh, so if I want to build a concrete LibreSSL version I should checkout this repo at that tag and set `OPENBSD_BRANCH` accordingly as well? Is this documented somewhere? It makes sense that that is the process, but a few lines in the README would help people so they do not have to go and dig into what `autogen.sh` or `update.sh` does. I can make a small PR that documents this in the README if you would like.

**Comment by orbea** [comment]
> Is there a way to satisfy both constraints?

If I understand correctly libressl is developed as part of the OpenBSD source tree itself rather than as its own unique project that is used within OpenBSD? Would you mind explaining why exactly for this aspect of the arrangement? I get that changing the workflow for OpenBSD developers would be no small ask, but in a more generic source tree for libressl might be less complicated for other users.

I am unfortunately ignorant of how OpenBSD's development process works to suggest other alternatives and its not a deal breaker for me if this situation doesn't change, but I very much appreciate the in depth explanations on why it is like it currently is.

**Comment by schwabe** [comment]
Are at least the tags themselves stable?  Then you could use a tag to check that out. I find it also a bit strange that if you checkout an old libressl version that you don't an old version but a mix of old and OpenBSD master.

```
      # LibreSSL has master in the OPENBSD_BRANCH by default even in the tagged releases
      # Manually use the OpenBSD branch that is more appropiate and remove git pull that
      # breaks when checking out a tag instead of branch
      - name: "libressl: fix build"
        run: |
           echo libressl-v3.7.0 > OPENBSD_BRANCH
           sed -i -e 's/ git pull --rebase//' update.sh
        working-directory: libressl
```

is the workaround/hack that I currently use for our github actions to get libressl compiling again.

**Comment by busterb** [comment]
> Oh, so if I want to build a concrete LibreSSL version I should checkout this repo at that tag and set OPENBSD_BRANCH accordingly as well? Is this documented somewhere?

If you want a release version of LibreSSL, your best bet is to download a release from a mirror: https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/

This is documented in the Readme.md file:

> Official release tarballs are available at your friendly neighborhood OpenBSD mirror in directory [LibreSSL](https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/), although we suggest that you use a [mirror](https://www.openbsd.org/ftp.html).

Setting the OPENBSD_BRANCH, etc. is not the way to get an official release.

**Comment by busterb** [comment]
> Are at least the tags themselves stable? 

The tags in this project, 'portable', are stable. The tags in the 'openbsd' repository can change any time there is a push to github since the underlying git hashes are not stable there. They will point to the same commit, but a different hash. These tags don't exist upstream on the openbsd side, so they have to be synthesized by the git conversion process too.

These tags also only appear _after_ we've built and shipped a release, so there's a chicken and egg situation here from a release procedure perspective. I started writing out the steps needed to do this, and after step 8 it got silly, just decided to say, please trust me when I say it's a non-starter. I think we really need stable git hashes to make this work without a lot of toil and error.

**Comment by busterb** [comment]
Something that might work without a lot of toil is if you could codify this logic into update.sh:

'if 'portable' is on a tagged commit, and the upstream 'openbsd' repo points to github
   checkout the corresponding tagged commit in the openbsd repo'
   
That doesn't solve the issue this ticket was raised for (that requires concrete work to update -portable instead https://github.com/libressl/portable/pull/816)

**Comment by busterb** [comment]
We just pinned master to a working upstream commit while we sort out the upstream changes. That should unbreak any regression tests and automation that are relying on this repo, but you still should use official release tarballs for things like production builds, etc.

In the mean time, taking a look at how we might use git subtrees to point at the more stable OpenBSD git mirror to selectively pull in the modules that this project uses. 
https://makingsoftware.wordpress.com/2013/02/16/using-git-subtrees-for-repository-separation/

**Comment by busterb** [comment]
Proposing a solution for _future_ tags with #830 . This adds logic to update.sh so that it will try to checkout the nearest commit in time in the event that an openbsd tag does not exist. This works whether we're in a stable branch or on master, and is the same logic used to generate the tags on the openbsd tree in the first place.

Due to a lack of branch support, using the upstream openbsd github mirror isn't going to work as a submodule or subtree.

**Comment by busterb** [comment]
Merge the change to the update script above for further testing in-tree.

Note, this will not retroactively fix any old tags, but just wanted to be clear!
