### ISSUE TITLE
3.7.1 build filed on mips and mipsel and mips64: bn_arch.h: No such file or directory

### ISSUE THREAD

**Issue by abcfy2** [libressl/portable#827]
```
  CC       bio/libcrypto_la-bss_mem.lo
  CC       bio/libcrypto_la-bss_null.lo
  CC       bio/libcrypto_la-bss_sock.lo
  CC       bn/libcrypto_la-bn_add.lo
bn/bn_add.c:65:10: fatal error: bn_arch.h: No such file or directory
   65 | #include "bn_arch.h"
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:6456: bn/libcrypto_la-bn_add.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/usr/src/libressl-3.7.1/crypto'
make[1]: *** [Makefile:2289: all] Error 2
make[1]: Leaving directory '/usr/src/libressl-3.7.1/crypto'
make: *** [Makefile:461: all-recursive] Error 1
Error: Process completed with exit code 2.
```

Full build log can be found in: https://github.com/abcfy2/aria2-static-build/actions/runs/4452919428/jobs/7821006858

**Comment by abcfy2** [comment]
But openssl 3.1.0 and previous version of libressl are working.

**Comment by 4a6f656c** [comment]
`bn_arch.h` is an internal header that is new to this release - mips and mipsel are not architectures that we develop or test on, hence the header is missing. In the case of an unknown architecture, we should be able to provide an empty `bn_arch.h` so that it at least compiles.

In the mips64 case, we do develop and test on this architecture - the errors there are due to missing symbols, which are provided by the assembly code (generated by `bn/asm/mips.pl`). Building with `OPENSSL_NO_ASM` would presumably avoid that, as would figuring out why the assembly is not being generated/included.

**Comment by busterb** [comment]
I've got a local patch that fixes this and mips64 (which was also broken). I'm planning on disabling all assembly for 32-bit mips because the o32 / n32 ABI split and the perl asm generators don't place nice together. Enabling it as-is for mips64 with the n64 ABI.

**Comment by busterb** [comment]
This will be resolved in the next release.
