### ISSUE TITLE
Use static analysis tool to detect bugs

### ISSUE THREAD

**Issue by jimying** [libressl/portable#835]
hi,  i think that we need use static analysis tool to detect bugs.

scan-build (a llvm util)   or  coverity(which is free for open source)

I had test scan-build in openbsd7.2 (with the release libressl3.7.2)
```bash
# install llvm (which contains scan-build)
pkg_add llvm
```

Here simplely show how to use scan-build:
```bash
JOBS=4
SCAN_BUILD="scan-build -o output"

make distclean
./configure ....

$SCAN_BUILD  make -j  $JOBS
```

The results:
```
All: 482    Logic error:  52       Memory error: 6      Security: 1      Unused code: 423
```

I think  "Unused code"  can ignore , but   the errors (Logic, memory)  need fix.

**Comment by botovq** [comment]
On Sun, Apr 09, 2023 at 08:53:17PM -0700, jimying wrote:
> hi,  i think that we need use static analysis tool to detect bugs.
> 
> scan-build (llvm util)   or  coverity(which is free for open source)

Thanks. We do use static analysis tools. The problem is that most of
them aren't very good.

We have had daily coverity runs since 2014. A good number of the things
it flags are simply incorrect. Just last night coverity found three new
"defects" in code I refactored. It claims there are memory leaks where
there aren't.

> ```
> All: 482    Logic error:  52       Memory error: 6      Security: 1      Unused code: 423
> ```

scan-build has a very high false positive rate and it is dificult to
find the actual bugs in all the noise it generates. If the path length
is longer than, say, 10, you can bet it makes self-contradictory
assumptions along the way.

The security error is about mktemp which isn't used in a problematic
way. The memory errors all are false positives. The logic errors I
looked at also aren't actual problems.

Another issue with scan-build is that you can't tell it when it's
wrong, so it won't learn.

And don't get me started on gcc or cppcheck.

If you find a bug using such tools and have a diff we will happily take
it. Other than that these tools have a high tendency of wasting our
time.
