### ISSUE TITLE
(CID 471971) crypto/ec/ec_ameth.c: checked return is suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [libressl/portable#985]
looks like we can mark this as "intended" in coverity (since we return 1) ?

```
*** CID 471971:  Error handling issues  (CHECKED_RETURN)
/home/runner/work/portable/portable/crypto/ec/ec_ameth.c: 558 in eckey_param_decode()
552     {
553             EC_KEY *eckey;
554             if (!(eckey = d2i_ECParameters(NULL, pder, derlen))) {
555                     ECerror(ERR_R_EC_LIB);
556                     return 0;
557             }
>>>     CID 471971:  Error handling issues  (CHECKED_RETURN)
>>>     Calling "EVP_PKEY_assign" without checking return value (as is done elsewhere 33 out of 38 times).
558             EVP_PKEY_assign_EC_KEY(pkey, eckey);
559             return 1;
560     }
561     
562     static int
563     eckey_param_encode(const EVP_PKEY *pkey, unsigned char **pder)
```

**Comment by botovq** [comment]
On Fri, Dec 29, 2023 at 02:41:55PM -0800, Ilya Shipitsin wrote:
> looks like we can mark this as "intended" in coverity (since we return 1) ?

Like all the other EVP_PKEY_assign issues flagged recently this is a
false positive. However, Coverity is rightly flagging bad code and I
fixed that in this commit, which will make it happy again:

https://github.com/openbsd/src/commit/976ea5e2c408889bebccdb346415a750a3f86d83

The problem is this: EVP_PKEY_assign_EC_KEY() wraps EVP_PKEY_assign with
a type of EVP_PKEY_EC, which means the EVP_PKEY_set_type() call can't
fail (that's not entirely obvious):

int
EVP_PKEY_assign(EVP_PKEY *pkey, int type, void *key)
{
	if (!EVP_PKEY_set_type(pkey, type))
		return 0;

	return (pkey->pkey.ptr = key) != NULL;
}

If EVP_PKEY_set_type() fails, the key leaks.

The reason all these show up is that I removed a micro-optimization
(the return 1 on line 257 here):

https://github.com/openbsd/src/commit/ca270c0af014226ef0d076452fa4b2b38e6235eb

Coverity can no longer tell that I didn't change behavior (with a
type of EVP_PKEY_EC, EVP_PKEY_asn1_find() will not fail).

**Comment by chipitsine** [comment]
thanks, let's wait for the next scheduled coverity check.
if the issue is gone, I'll close this issue

**Comment by botovq** [comment]
It's a bit off-topic, but do you happen to have received a notification
what that finding of the run from about 26 hours ago was about?

```
    Build ID: 583748

    Analysis Summary:
       New defects found: 1
       Defects eliminated: 0
```

I did not receive a mail with the details and I am unable to find anything
on their site.

**Comment by chipitsine** [comment]
I'll check

**Comment by chipitsine** [comment]
I didn't receive any notification (even in spam).
also, I do not see any recent finding in https://scan.coverity.com

I beleive it was an internal coverity bug

**Comment by botovq** [comment]
On Sun, Jan 14, 2024 at 10:02:06AM -0800, Ilya Shipitsin wrote:
> I didn't receive any notification (even in spam).
> also, I do not see any recent finding in https://scan.coverity.com

Thanks a lot. That matches my experience.
(This must be a candiate for the worst webpage ever).

> I beleive it was an internal coverity bug

:)
